### ISSUE TITLE
执行composer require lake/lake-admin时报错

### ISSUE THREAD

**Issue by hai191273** [deatil/lake-admin#11]
PHP Fatal error:  Trait 'Lake\Admin\Http\Traits\Jump' not found in /www/wwwroot/lake-admin.xinhuacaipiao.net/vendor/lake/lake-admin/src/lake/admin/Controller/Base.php on line 17

![image](https://user-images.githubusercontent.com/3326158/114147108-eeebea00-994a-11eb-9044-4ef60bdd315e.png)

**Comment by deatil** [comment]
你tp框架用的版本号是多少？lake-admin系统的这个版本号有点问题，你把thinkphp的版本号调到最新在 `composer update ` 试下
