### ISSUE TITLE
登录时总提示用户名或密码错误

### ISSUE THREAD

**Issue by vipbuy** [deatil/lake-admin#3]
登录时总提示用户名或密码错误，有QQ吗，联系你，二开

**Comment by deatil** [comment]
密码这个我查下是哪的问题

**Comment by vipbuy** [comment]
本地我用本地换进 php7.3  apache mysql5.7 完全按你写的方式安装的，数据库都正常，可是登录时，总提示用户名或密码错误

**Comment by vipbuy** [comment]
本地我用本地换进 php7.3  apache mysql5.7 完全按你写的方式安装的，数据库都正常，可是登录时，总提示用户名或密码错误

**Comment by deatil** [comment]
> 本地我用本地换进 php7.3 apache mysql5.7 完全按你写的方式安装的，数据库都正常，可是登录时，总提示用户名或密码错误

可以了。数据库的密码某个版本没更新到，出现的问题。重新拉取新版本

**Comment by vipbuy** [comment]
谢谢，我测试一下，我非常喜欢这个

**Comment by vipbuy** [comment]
您确定能进后台吗  admin/123456 试了，还是进不去，我全新下载安装的

**Comment by deatil** [comment]
> 您确定能进后台吗 admin/123456 试了，还是进不去，我全新下载安装的

以前的数据库删了重新安装下，或者用新版的自己重置下密码。新版的文档里的重置密码命令

**Comment by deatil** [comment]
重置密码
~~~
php think lake-admin:reset-password
~~~

**Comment by vipbuy** [comment]
安装 thinkphp6.0 框架
配置数据库的连接信息
composer require lake/lake-admin 导入lake-admin后台管理系统
执行 php think lake-admin:install 及 php think lake-admin:service-discover 初始化 lake-admin 系统
设置网站执行目录为：public
部分自定义配置，需要将根目录 .env.lake 文件里内容复制到 .env 内
主要就做了这几步，看来是不会安装，文件不全，所以才提示 帐号密码不对。真的没有玩过，搞不定了。

**Comment by deatil** [comment]
> 安装 thinkphp6.0 框架
> 配置数据库的连接信息
> composer require lake/lake-admin 导入lake-admin后台管理系统
> 执行 php think lake-admin:install 及 php think lake-admin:service-discover 初始化 lake-admin 系统
> 设置网站执行目录为：public
> 部分自定义配置，需要将根目录 .env.lake 文件里内容复制到 .env 内
> 主要就做了这几步，看来是不会安装，文件不全，所以才提示 帐号密码不对。真的没有玩过，搞不定了。

不是文件不全，是数据库里的账号密码存的是以前的，所以会有点问题，新的就没有问题了。你用composer看下下载的是哪个版本的

**Comment by vipbuy** [comment]
Composer version 2.0.8 2020-12-03 17:20:38

**Comment by vipbuy** [comment]
我数据库彻底删除，然后执行上面的步骤，操作了好多次，之前都是git pull拉取的，所以composer安装没有操作过。所以可能根本就没有弄对

**Comment by deatil** [comment]
> 我数据库彻底删除，然后执行上面的步骤，操作了好多次，之前都是git pull拉取的，所以composer安装没有操作过。所以可能根本就没有弄对

你安装完后，确认下 'src/lake/admin/Command/ResetPassword.php' 这个文件存不存在，在的话就是最新的

**Comment by vipbuy** [comment]
\vendor\lake\lake-admin\src\lake\admin\Command 下面还真没有ResetPassword.php ，我全删除重新操作一次
