### ISSUE TITLE
之前一直用git拉取，你这种安装方式，怎么更新最新的程序

### ISSUE THREAD

**Issue by vipbuy** [deatil/lake-admin#4]
之前一直用git拉取，你这种安装方式，怎么更新最新的程序，是用composer update吗

**Comment by deatil** [comment]
是的。composer update更新

**Comment by vipbuy** [comment]
是不是 应该先把 composer.json 补全了（弄了半天，还是不对），然后再composer update是吧

**Comment by deatil** [comment]
> 是不是 应该先把 composer.json 补全了（弄了半天，还是不对），然后再composer update是吧

新版的是2.3.25，你可以手动修改composer.json的版本为2.3.25，再用composer update更新，数据源需要确认对应的版本已经同步了

**Comment by vipbuy** [comment]
"require": {
        "php": ">=7.1.0",
        "topthink/framework": "^6.0.0",
        "topthink/think-orm": "^2.0",
        "lake/lake-admin": "^2.3.25"
    },
我手动修改成了2.3.25 现在正在下载

**Comment by vipbuy** [comment]
github太慢了，下到50%不动了，国内用gitee还是快

**Comment by deatil** [comment]
> github太慢了，下到50%不动了，国内用gitee还是快

换个国内的仓库源。composer没法下载gitee的

**Comment by vipbuy** [comment]
换成阿里的，几秒搞定，谢谢，主要这个用的太少了，这么low的问题，打扰你了

**Comment by vipbuy** [comment]
下载完tp6,运行composer require lake/lake-admin后lake/lake-admin版本变成了2.3，安装还还是老版，我强行修改成 2.3.25后，应该下载的是最新的，然后在php think lake-admin:install 安装时 数据库安装报错了
 You can set a dbpre (enter skip):
 >
Lake-admin tip: import sql is error!

**Comment by deatil** [comment]
> 下载完tp6,运行composer require lake/lake-admin后lake/lake-admin版本变成了2.3，安装还还是老版，我强行修改成 2.3.25后，应该下载的是最新的，然后在php think lake-admin:install 安装时 数据库安装报错了
> You can set a dbpre (enter skip):
> 
> > 
> 
> Lake-admin tip: import sql is error!

你把数据库删了重新再安装下看看

**Comment by vipbuy** [comment]
还是安装数据库时报错

**Comment by deatil** [comment]
> 还是安装数据库时报错，数据库只安装了5个表
> ![image](https://user-images.githubusercontent.com/77948523/105970739-a8fde480-60c4-11eb-8f7e-08b166c0f60f.png)

好了，数据库设计有点问题，优化了下可以了
