### ISSUE TITLE
用composer require lake/lake-admin-cms下载的模块后台找不到

### ISSUE THREAD

**Issue by vipbuy** [deatil/lake-admin#9]
composer require lake/lake-admin-cms下载的模块，是下载到了 \vendor\lake 下面是对的，谢谢！

**Comment by vipbuy** [comment]
刚才手动复制到了addon下面、后来composer update时 \vendor\lake 下面又多一份，到底是应该下载到哪个下面

**Comment by deatil** [comment]
模版在 `/public/template` 里面

**Comment by deatil** [comment]
对的，composer基本都在 ` \vendor\lake` 这个目录
